### ISSUE TITLE
if ajax data is not a string it throws an error

### ISSUE THREAD

**Issue by spunkedy** [emadalam/atvjs#10]
Attached an example. I might do a PR to detect if an object and xml encode it.
![screen shot 2016-04-02 at 4 35 58 pm](https://cloud.githubusercontent.com/assets/690735/14229150/16ca5354-f8f1-11e5-8e90-9a17bb2d1313.png)

**Comment by emadalam** [comment]
@spunkedy Thanks for pointing this out. However, it's not an error and the behaviour is left intentional. According to the description of the `send` method of [TVJS XMLHttpRequest Class Reference](https://developer.apple.com/library/tvos/documentation/TVMLJS/Reference/TVJSXMLHttpRequest_Ref/index.html#//apple_ref/javascript/instm/XMLHttpRequest/send), it supports `Object` as its parameter and the object should be of type `ArrayBufferView` or `Blob` or `Document` or `DOMString` or `FormData`. Read [MDN](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#send())'s developer documentation for details.

Having said that, the support for plain data objects and other jazzy features (like those supported by [jQuery's ajax](http://api.jquery.com/jquery.ajax/)) can be implemented, but it's an overkill. The focus of this library is to be as minimalistic as possible and provide the flexibility to the users to get started quickly, hence the ajax library is mostly just a `Promise` based wrapper around the native XHR. You can simply use something as simple as `JSON.stringify` to achieve the desired results.
```js
ATV.Ajax
    .post('path/to/the/post/api', {
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded' // or 'application/json' if your server supports it
        },
        data: JSON.stringify(your_data_object)
    })
    .then(function(xhr) {
        // success
    }, function(xhr) {
        // error
    });
```
To me adding such features will eventually divert the main focus of this library, as it's not intended to be a replacement of other libraries and neither a competition to them. Let me know what you think, really appreciate your contribution 👍

**Comment by spunkedy** [comment]
Your logic is sound. I added a wrapper for what I needed specifically ( JSON.stringify ). Maybe I will post a google analytics example data post in the readme.
